---
- hosts: ws
  become: true
  become_user: root
  tasks:
  - name: Install prerequisites
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common']
      update_cache: yes

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} edge

  - name: Install Docker
    apt:
      name: docker.io
      state: present
      update_cache: yes
